services:
  registry-radar:
    image: ghcr.io/andrewbusbee/registry-radar:0.1.0-beta.4 # Tag will become latest when released
    container_name: registry-radar
    ports:
      - "3001:3001"
    volumes:
      - data:/app/data
    environment:
      - NODE_ENV=production
      - PORT=3001
      - APPRISE_URL=http://apprise:8000
      # Docker Hub Authentication (optional)
      # Increases rate limit from 100 to 200 pulls/6hr (or unlimited with Pro account)
      # Uncomment and set your credentials to enable:
      # - DOCKERHUB_USERNAME=your_username
      # - DOCKERHUB_PASSWORD=your_password_or_token
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "node", "-e", "require('http').get('http://localhost:3001/api/cron/status', (res) => { process.exit(res.statusCode === 200 ? 0 : 1) })"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    networks:
      - registry-radar-network

  apprise:
    image: caronc/apprise:latest
    container_name: apprise
    ports:
      - "8000:8000"
    environment:
      - APPRISE_ALLOW_HOSTS=registry-radar # Only allow connections from registry-radar container
    restart: unless-stopped
    networks:
      - registry-radar-network

volumes:
  data:

networks:
  registry-radar-network:
    driver: bridge
    name: registry-radar-network
